spring.application.name=opd_token_alloc
spring.datasource.url=***************
spring.datasource.username=*******
spring.datasource.password=**********
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect